import type { MessageKey } from '../../i18n';

export const SHORTCUT_GROUPS: { title: MessageKey; items: [MessageKey, string][] }[] = [
  {
    title: 'shortcuts.tools',
    items: [
      ['tool.move', 'V'],
      ['tool.select', 'M'],
      ['tool.hand', 'H'],
      ['tool.pencil', 'B'],
      ['tool.lassoFill', 'K'],
      ['tool.eraser', 'E'],
      ['tool.bucket', 'G'],
      ['tool.line', 'L'],
      ['tool.rect', 'R'],
      ['tool.ellipse', 'C'],
      ['tool.shade', 'S'],
      ['tool.lighten', 'O'],
      ['tool.blur', 'F'],
      ['tool.spray', 'A'],
      ['tool.jumble', 'J'],
      ['tool.liquify', 'W'],
      ['tool.picker', 'I / Alt'],
    ],
  },
  {
    title: 'shortcuts.drawing',
    items: [
      ['options.size', '1 – 9'],
      ['color.swap', 'X'],
      ['menu.undo', 'Ctrl+Z'],
      ['menu.redo', 'Ctrl+Shift+Z'],
      ['shortcuts.clipboard', 'Ctrl+C / X / V'],
      ['menu.copySvg', 'Ctrl+Shift+C'],
      ['shortcuts.clear', 'Del'],
      ['menu.fillLayer', 'Shift+Del'],
      ['shortcuts.nudge', '← → ↑ ↓ (Shift)'],
      ['menu.flipH', 'Shift+H'],
      ['menu.flipV', 'Shift+V'],
      ['menu.rotate', 'Shift+R'],
      ['menu.rotateLeft', 'Alt+Shift+R'],
      ['shortcuts.align', 'Alt+A / H / D, Alt+W / V / S'],
    ],
  },
  {
    title: 'shortcuts.layers',
    items: [
      ['layer.new', 'Shift+N'],
      ['layer.duplicate', 'Shift+D'],
      ['layer.mergeDown', 'Shift+M'],
      ['group.create', 'Ctrl+G'],
      ['group.ungroup', 'Ctrl+Shift+G'],
      ['shortcuts.deleteLayer', 'Del'],
      ['adjust.outline', 'Shift+O'],
      ['menu.layerUp', 'Alt+↑'],
      ['menu.layerDown', 'Alt+↓'],
    ],
  },
  {
    title: 'shortcuts.view',
    items: [
      ['shortcuts.pan', 'Space + drag'],
      ['shortcuts.zoom', 'Wheel, + / −, Ctrl+= / Ctrl+-'],
      ['zoom.fit', 'Shift+1'],
      ['shortcuts.actualSize', 'Shift+0'],
      ['menu.grid', 'Shift+G'],
      ['menu.tile', 'Shift+T'],
      ['shortcuts.mirror', 'Shift+X / Shift+Y'],
      ['menu.preview', 'Shift+P'],
      ['menu.hideUi', 'Tab / @'],
      ['menu.commandPalette', 'Ctrl+K'],
      ['menu.open', 'Ctrl+O'],
      ['menu.renameFile', 'F2'],
      ['menu.export', 'Ctrl+E'],
      ['menu.adjustColors', 'Ctrl+U'],
    ],
  },
];
